### ISSUE TITLE
Client should broadcast an event when a commit is accepted

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-ontology-client#29]
see https://github.com/protegeproject/protege-server/issues/26 for background. This is necessary to fix https://github.com/protegeproject/protege-client/issues/18.

**Comment by bdionne** [comment]
not sure this is really necessary. What's the behavior of prompt diff when the user explicitly does a `server/update`?

I ask because when I select the prompt diff tab then choose the user who is logged in, I see the latest commits in the commits panel in the lower left. So it must be fetching them or getting them locally. What doesn't work is seeing the details of those commits.

As a workaround, if I click download, .eg., then cancel, I can now see the commit's details. So I'm wondering if this is just a refresh issue? Especially if I do a `server/update`, shouldn't prompt diff refresh in that case?

**Comment by rsgoncalves** [comment]
Most views like the author and commit views will get updated directly when the user does `update`. But the change details view works differently: It uses some cached data for faster fetching of changes, e.g., by date, or by commit. It's not a UI refresh issue, it's the data structures that haven't been updated yet. The diff engine needs to update its local caches once a commit arrives on the server.

**Comment by bdionne** [comment]
I see, this explains what I see in the debugger. So perhaps some sort of event or notification is needed from the client. For the client who does the commit, the data is in the versioned ontology history so prompt diff should be able to get a hold of it

**Comment by johardi** [comment]
Closes via https://github.com/protegeproject/protege-client/commit/5a0c5fd465a5aaa8fc9c8b5d4d906de45ea5577d

**Comment by bdionne** [comment]
reopening for clarification. Not sure how this relates to #18. This commit creates events when changes within a commit are accepted and then committed with prompt diff. As an aside this accept/commit operation is a noop. The problem described in #18 relates to when there are changes made in the editor and committed using `server/commit`. The commit itself shows up in the commit panel of prompt diff, but no changes appear in details if you select it. 

Feel free to close this again if I'm missing something

**Comment by johardi** [comment]
Thank you for the correction Bob. I just realized the event is for commit command coming from protege-client, rather than from prompt-diff.

**Comment by rsgoncalves** [comment]
Please do not do anything about this. I'm taking care of it and have a fix in the pipeline.
